joint_a1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_a1
    pid: {p: 500.0, i: 5.0, d: 180.0}

joint_a2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_a2
    pid: {p: 500.0, i: 5.0, d: 180.0}
    
joint_a3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_a3
    pid: {p: 500.0, i: 5.0, d: 180.0}

joint_a4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_a4
    pid: {p: 500.0, i: 5.0, d: 180.0}

joint_a5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_a5
    pid: {p: 500.0, i: 5.0, d: 180.0}
    
joint_a6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_a6
    pid: {p: 500.0, i: 5.0, d: 180.0}



# pos_controller:
#   type: "effort_controllers/JointPositionController"
#   joints:
#      - joint_a1
#      - joint_a2
#      - joint_a3
#      - joint_a4
#      - joint_a5
#      - joint_a6
#   pid_gains:
#     joint_a1: {p: 300.0, i: 0.1, d: 30.0}
#     joint_a2: {p: 100.0, i: 0.1, d: 10.0}
#     joint_a3: {p: 100.0, i: 0.1, d: 10.0}
#     joint_a4: {p: 100.0, i: 0.1, d: 10.0}
#     joint_a5: {p: 10.0, i: 0.1, d: 1.0}
#     joint_a6: {p: 10.0, i: 0.1, d: 1.0}



# pos_controller:
#   type: "position_controllers/JointGroupPositionController"
#   joints:
#      - joint_a1
#      - joint_a2
#      - joint_a3
#      - joint_a4
#      - joint_a5
#      - joint_a6
#   pid_gains:
#     joint_a1: {p: 300.0, i: 0.1, d: 30.0}
#     joint_a2: {p: 100.0, i: 0.1, d: 10.0}
#     joint_a3: {p: 100.0, i: 0.1, d: 10.0}
#     joint_a4: {p: 100.0, i: 0.1, d: 10.0}
#     joint_a5: {p: 10.0, i: 0.1, d: 1.0}
#     joint_a6: {p: 10.0, i: 0.1, d: 1.0}

