arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - joint_a1
     - joint_a2
     - joint_a3
     - joint_a4
     - joint_a5
     - joint_a6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint_1: {trajectory: 0.1, goal: 0.1}
      joint_2: {trajectory: 0.1, goal: 0.1}
      joint_3: {trajectory: 0.1, goal: 0.1}
      joint_4: {trajectory: 0.1, goal: 0.1}
      joint_5: {trajectory: 0.1, goal: 0.1}
      joint_6: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

# pos_controller:
#   type: "position_controllers/JointGroupPositionController"
#   joints:
#      - joint_a1
#      - joint_a2
#      - joint_a3
#      - joint_a4
#      - joint_a5
#      - joint_a6
#   pid_gains:
#     joint_a1: {p: 100.0, i: 0.01, d: 10.0}
#     joint_a2: {p: 100.0, i: 0.01, d: 10.0}
#     joint_a3: {p: 100.0, i: 0.01, d: 10.0}
#     joint_a4: {p: 100.0, i: 0.01, d: 10.0}
#     joint_a5: {p: 100.0, i: 0.01, d: 10.0}
#     joint_a6: {p: 100.0, i: 0.01, d: 10.0}